groups:
- jobs:
  - build
  name: build
- jobs:
  - pipeline
  name: pipeline-update
jobs:
- name: pipeline
  plan:
  - get: thatsamguy-web
    trigger: true
  - file: thatsamguy-web/pipeline.yml
    set_pipeline: thatsamguy-web
- name: build
  on_error:
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :boom: A build of $BUILD_PIPELINE_NAME errored. Check it out <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|here>.
      username: concourse
    put: notify
  on_failure:
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :boom: A build of $BUILD_PIPELINE_NAME failed. Check it out <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|here>.
      username: concourse
    put: notify
  on_success:
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :airplane_departure: A new build of $BUILD_PIPELINE_NAME deployed! Check it out <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|here>.
      username: concourse
    put: notify
  plan:
  - get: thatsamguy-web
    passed:
    - pipeline
    trigger: true
  - config:
      image_resource:
        source:
          repository: ghcr.io/getzola/zola
          tag: "v0.22.1"
        type: registry-image
      inputs:
      - name: thatsamguy-web
      outputs:
      - name: built-site
      platform: linux
      run:
        path: zola
        args:
        - build
        - --output-dir
        - ../../built-site/public
        dir: thatsamguy-web/website
    task: build
  - config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: amazon/aws-cli
          tag: latest
      inputs:
      - name: built-site
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo "Syncing to S3..."
          ls -1 built-site/public/ || exit
          aws s3 sync built-site/public/ s3://aws-website-thatsamguy-00trx/ \
            --delete \
            --region us-east-1 \
            --exclude ".git/*" \
            --exclude "wu/*"

          # 2. (Optional) Invalidate CloudFront
          # echo "Invalidating CloudFront..."
          # aws cloudfront create-invalidation --distribution-id YOUR_DIST_ID --paths "/*"
    params:
      # Pass credentials as env vars
      AWS_ACCESS_KEY_ID: ((aws-access-key-id))
      AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
      AWS_DEFAULT_REGION: us-east-1
    task: deploy
resource_types:
- name: slack-notification
  source:
    repository: cfcommunity/slack-notification-resource
  type: docker-image
resources:
- icon: github
  name: thatsamguy-web
  source:
    branch: main
    ignore_paths:
    - pipeline-letsencrypt.yml
    password: ((github-password))
    private_key: ((github-private-key))
    uri: git@github.com:thatsamguy/thatsamguy-web.git
    username: ((github-username))
  type: git
- icon: slack
  name: notify
  source:
    url: ((slack-webhook))
  type: slack-notification
